### ISSUE TITLE
Example Usage

### ISSUE THREAD

**Issue by JoelBCarter** [SiebeSysmans/insomnia-plugin-jwtdecode#1]
This is a fantastic plugin, I'm just wondering how you're using it.  I've got it decoding static values that I paste in which saves me from having to hop out of Insomnia to [JWT.io](https://jwt.io/), I'm just wondering if there's a way to have to have it be part of the response life-cycle and automatically display the decoded JWT fields for me.  I feel like I'm missing something.

**Comment by kuba-tyburski** [comment]
I'm trying to use it ith Insomnia 5.16.6 but when I install it with Plugin tab of preferences, nothing changes. There is nothing in Tools menu besides 'Reload plugins' option. In dev tools I can see log that plugin has loaded. Any idea? Is it not supported by this version of node?

![image](https://user-images.githubusercontent.com/1963159/42676628-2f4a0a60-8679-11e8-86df-7f58b436cdc4.png)

**Comment by edjroz** [comment]
Same issue here

**Comment by sukima** [comment]
Seriously! How do you use this plugin?!

**Comment by gabrielkrell** [comment]
Same here; wondering if this is broken (since plugins are still in development) or there's just some arcane way to pull it in.

**Comment by SiebeSysmans** [comment]
Hi, I've added some screenshots to the readme of how I use this plugin in Insomnia to reference JWT values in other requests. Hope this helps.

**Comment by sukima** [comment]
Oh! This plugin is **not** for viewing/inspecting/validating/constructing JWT tokens! Well that was misleading.

**Comment by SiebeSysmans** [comment]
No indeed, it's only for decoding as the name of the plugin implies.
