### ISSUE TITLE
Some values once decoded show up as [object Object]

### ISSUE THREAD

**Issue by cmcneal** [SiebeSysmans/insomnia-plugin-jwtdecode#2]
Just wanted to note, this is a great plugin, saves moving out of insomnia. The we use it is to have a variable defined that contains the token, then in the **Docs** tab I use this plugin to decode the various values and display them.

![jwtdecode-plugin-example](https://user-images.githubusercontent.com/1855384/48587839-eca81180-e8f1-11e8-965f-ae331f785b4f.png)

There is one slight issue, and that is that one field, once decoded, is showing up as `[object Object]`.

Example:

```
https://sample/_tids: {
  _tid_0ccccc00-00c0-00c0-cccc-c00cc00000cc: true
 },
```

is displayed as 
```
"tids": [object Object],
```

Locally I have simply added a `JSON.stringify(claimResult)` as this solves the problem for my usage.

**Comment by SiebeSysmans** [comment]
Will be fixed in the next release due to https://github.com/SiebeSysmans/insomnia-plugin-jwtdecode/pull/4
